# Generated by Django 4.2.11 on 2025-06-29 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0002_bookings_customer_bookings_provider_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='additional_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bookings',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='preferred_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='urgency_level',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
