# Generated by Django 4.2.11 on 2025-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0003_bookings_additional_notes_bookings_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
